(() => {
 const $=id=>document.getElementById(id),owners=new Set(['mario@memberhq.net','mpenalver@bethelsd.org','astramario@gmail.com']);let events=[],shown=[],epoch=0,loaded=false,pending=false;
 const node=(tag,text)=>{const n=document.createElement(tag);n.textContent=String(text??'');return n;},seconds=ms=>ms==null?'—':(ms/1000).toFixed(2)+'s';
 const explanation=e=>e.status===0?'Network request did not complete':e.status===401?'Sign-in rejected or expired':e.status===403?'Permission denied':e.status===429?'Too many attempts':e.status>=500?'Service unavailable or timed out':e.status>=400?'Request rejected':'Success';
 function clear(){epoch++;loaded=false;pending=false;$('diagnostics-refresh').disabled=false;events=[];shown=[];$('diagnostics-workspace').hidden=true;$('diagnostics-rows').replaceChildren();$('diagnostics-summary').replaceChildren();$('diagnostics-report').value='';$('diagnostics-search').value='';$('diagnostics-status').textContent='This dashboard is private to the NEST owner.';}
 function attempts(){const map=new Map();for(const e of events){let item=map.get(e.requestId);if(!item){item={...e,browserMs:null,serverMs:null};map.set(e.requestId,item);}if(e.phase==='browser'){Object.assign(item,e);item.browserMs=e.durationMs;}else{item.serverMs=e.durationMs;if(item.browserMs==null)Object.assign(item,e);}}return [...map.values()].sort((a,b)=>b.time.localeCompare(a.time));}
 function report(rows){return ['NEST™ access diagnostics · '+new Date().toISOString(),'Selected records: '+rows.length,'No passwords, codes, session tokens or ticket contents.',...rows.map(e=>['Time: '+e.time,'Account: '+e.actor+' ('+e.identity+')','Area/action: '+e.area+' / '+e.operation,'Result: '+explanation(e)+' · '+e.code+' · HTTP '+e.status,'Wait: browser '+seconds(e.browserMs)+'; server '+seconds(e.serverMs),'Request ID: '+e.requestId].join('\n'))].join('\n\n');}
 async function copy(rows){$('diagnostics-report').value=report(rows);try{await navigator.clipboard.writeText($('diagnostics-report').value);$('diagnostics-status').textContent='Copied. Paste this report into our discussion.';}catch{$('diagnostics-report').focus();$('diagnostics-report').select();$('diagnostics-status').textContent='Report selected below. Copy it with your keyboard.';}}
 function render(){
  const hours=$('diagnostics-period').value,area=$('diagnostics-area').value,outcome=$('diagnostics-outcome').value,search=$('diagnostics-search').value.toLowerCase();shown=attempts().filter(e=>(hours==='all'||Date.now()-Date.parse(e.time)<=Number(hours)*3600000)&&(!area||e.area===area)&&(!search||[e.actor,e.requestId,e.operation,e.code].join(' ').toLowerCase().includes(search))&&(outcome==='all'||outcome==='errors'&&(e.status===0||e.status>=400)||outcome==='slow'&&Math.max(e.browserMs||0,e.serverMs||0)>=5000));
  const waits=shown.map(e=>e.browserMs??e.serverMs??0).sort((a,b)=>a-b),average=waits.length?waits.reduce((a,b)=>a+b,0)/waits.length:0,p95=waits.length?waits[Math.max(0,Math.ceil(waits.length*.95)-1)]:0;
  $('diagnostics-summary').replaceChildren(...[['Attempts',shown.length],['Errors',shown.filter(e=>e.status===0||e.status>=400).length],['Average wait',seconds(average)],['95% within',seconds(p95)]].map(([label,value])=>{const card=node('div','');card.append(node('strong',value),node('span',label));return card;}));$('diagnostics-rows').replaceChildren();$('diagnostics-count').textContent=shown.length+' matching attempts. Showing the most recent '+Math.min(500,shown.length)+'. Copy report includes all matches.';
  shown.slice(0,500).forEach(e=>{const row=node('tr','');if(e.status===0||e.status>=400)row.className='diagnostics-error';[new Date(e.time).toLocaleString(),e.actor+' ('+e.identity+')',e.area+' / '+e.operation,explanation(e)+' · '+e.code,seconds(e.browserMs)+' / '+seconds(e.serverMs)].forEach(value=>row.append(node('td',value)));const cell=node('td',''),button=node('button',e.status===0||e.status>=400?'Copy error':'Copy details');button.type='button';button.addEventListener('click',()=>copy([e]));cell.append(button,node('small',e.requestId));row.append(cell);$('diagnostics-rows').append(row);});
 }
 async function load(){
  const identity=window.NestAuth?.identity;if(!identity?.signedIn||!owners.has(String(identity.email).toLowerCase())){clear();return;}pending=true;const current=++epoch;$('diagnostics-status').textContent='Loading private access records…';$('diagnostics-refresh').disabled=true;
  try{const response=await fetch('/api/diagnostics',{credentials:'same-origin',cache:'no-store',signal:AbortSignal.timeout(30000)}),data=await response.json();if(current!==epoch)return;if(!response.ok)throw new Error(data.error||'Records unavailable.');loaded=true;events=data.events||[];$('diagnostics-workspace').hidden=false;render();$('diagnostics-status').textContent=events.length?'Records updated.':'No records yet. New login and access attempts will appear here.';}catch(error){if(current===epoch){events=[];shown=[];$('diagnostics-rows').replaceChildren();$('diagnostics-summary').replaceChildren();$('diagnostics-workspace').hidden=true;$('diagnostics-report').value='';$('diagnostics-status').textContent=error.message;}}finally{if(current===epoch){pending=false;$('diagnostics-refresh').disabled=false;}}
 }
 ['diagnostics-period','diagnostics-area','diagnostics-outcome','diagnostics-search'].forEach(id=>$(id).addEventListener('input',render));$('diagnostics-refresh').addEventListener('click',load);$('diagnostics-copy').addEventListener('click',()=>copy(shown));document.addEventListener('nest-profile-tab-change',()=>queueMicrotask(ensureLoaded));document.addEventListener('nest-auth-change',()=>{clear();ensureLoaded();});window.addEventListener('pagehide',clear);Promise.resolve(window.NestAuth?.ready).then(ensureLoaded);
 function ensureLoaded(){const panel=$('profile-diagnostics-panel');if(panel&&!panel.hidden&&!$('profile-signed-in').hidden&&!loaded&&!pending)load();}
})();
