(() => {
  const status=document.getElementById('weather-status'),buttons=document.getElementById('weather-divisions'),section=document.getElementById('weather-data');
  const label=period=>period==='CTSO'?'NEST Robotics':'Division '+period;
  const pages=document.getElementById('weather-pages'),prev=document.getElementById('weather-prev'),next=document.getElementById('weather-next');let selected='';
  let request=0;
  async function get(period,page=0){const response=await fetch('/api/weather?period='+encodeURIComponent(period)+'&page='+page,{credentials:'same-origin',cache:'no-store'});const data=await response.json();if(!response.ok)throw new Error(data.error||'Weather reports unavailable.');return data;}
  function clear(){request++;selected='';pages.hidden=true;buttons.replaceChildren();section.hidden=true;section.querySelector('thead').replaceChildren();section.querySelector('tbody').replaceChildren();}
  async function show(period,page=0){selected=period;const current=++request;status.textContent='Loading '+label(period)+'…';section.hidden=true;try{const data=await get(period,page);if(current!==request)return;document.getElementById('weather-title').textContent=data.division;const head=document.createElement('tr');data.columns.forEach(value=>{const cell=document.createElement('th');cell.textContent=String(value);head.append(cell);});section.querySelector('thead').replaceChildren(head);const body=document.createDocumentFragment();data.rows.forEach(row=>{const tr=document.createElement('tr');data.columns.forEach((_,i)=>{const td=document.createElement('td');td.textContent=String(row[i]??'');tr.append(td);});body.append(tr);});section.querySelector('tbody').replaceChildren(body);section.hidden=false;pages.hidden=false;prev.disabled=page===0;next.disabled=!data.hasMore;document.getElementById('weather-page-label').textContent='Page '+(page+1);status.textContent=data.rows.length?`${data.rows.length} rows on this page of ${data.division}.`:'No report rows on this page.';}catch(error){if(current===request)status.textContent=error.message;}}
  async function load(){clear();if(!window.NestAuth?.identity?.signedIn){status.replaceChildren('Sign in to see your divisions. ');const sign=document.createElement('button');sign.type='button';sign.textContent='NEST sign in';sign.addEventListener('click',()=>window.NestAuth?.open());status.append(sign);return;}status.textContent='Checking access…';try{const data=await get('mine');if(!window.NestAuth?.identity?.signedIn)return;buttons.replaceChildren();data.periods.forEach(period=>{const button=document.createElement('button');button.type='button';button.textContent=label(period);button.addEventListener('click',()=>show(period));buttons.append(button);});status.textContent=data.periods.length?'Select a division.':'No weather report divisions are assigned to your NEST account.';}catch(error){status.textContent=error.message;}}
  prev.addEventListener('click',()=>{const page=Number(document.getElementById('weather-page-label').textContent.replace('Page ',''))-1;if(selected&&page>0)show(selected,page-1);});
  next.addEventListener('click',()=>{const page=Number(document.getElementById('weather-page-label').textContent.replace('Page ',''))-1;if(selected)show(selected,page+1);});
  document.addEventListener('nest-auth-change',load);window.NestAuth?.ready.then(load);
})();
