import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import {JSDOM} from 'jsdom';
import {diagnosticEvent,browserDiagnostic,withDiagnostics} from '../lib/diagnostics.mjs';import handler from '../api/diagnostics.mjs';import {COOKIE,IDENTITY,signedIdentity} from '../lib/nest-auth.mjs';
const requestId='11111111-1111-4111-8111-111111111111',id='22222222-2222-4222-8222-222222222222',session='a'.repeat(64),entry={id,requestId,time:'2026-10-04T17:00:00Z',area:'auth',operation:'login',phase:'server',status:503,durationMs:14000,actor:'student',identity:'attempted',code:'http-503'};
function response(){return {statusCode:200,headers:{},setHeader(k,v){this.headers[k]=v;},status(code){this.statusCode=code;return this;},json(data){this.data=data;return this;}};}
function school(){const props=new Map(),rows=[],created=[],permissions=[],writes=[];let held=false;const ctx=vm.createContext({Date,Map,Number,OWNER_EMAILS:['mario@memberhq.net','mpenalver@bethelsd.org','astramario@gmail.com'],email_:v=>String(v||'').toLowerCase(),PropertiesService:{getScriptProperties:()=>({getProperty:k=>props.get(k)||null,setProperty:(k,v)=>props.set(k,v)})},LockService:{getScriptLock:()=>({tryLock:()=>{held=true;return true;},releaseLock(){held=false;}})},authSession_:value=>value==='owner'?{email:'mario@memberhq.net',username:'mario'}:value==='student'?{email:'student@students.bethelsd.org',username:'student'}:null,Drive:{Permissions:{list:()=>({permissions:[{id:'owner',role:'owner'},{id:'domain',role:'reader'}]}),remove:(_id,p)=>permissions.push(p)}},Sheets:{Spreadsheets:{create:body=>{assert.equal(held,false);created.push(body);return {spreadsheetId:'private'};},Values:{update(){},get:()=>({values:rows}),batchUpdate:body=>{assert.equal(held,false);writes.push(body);rows.push(...body.data.flatMap(d=>d.values));}}}}});vm.runInContext(fs.readFileSync('google-spinner/Diagnostics.js','utf8'),ctx);return {ctx,props,rows,created,permissions,writes};}
test('metadata selects only fixed fields and marks attempted usernames, with no password, ticket contents or cookie persistence',()=>{
 const old=process.env.SPINNER_BRIDGE_TOKEN;process.env.SPINNER_BRIDGE_TOKEN='test-secret';try{const event=diagnosticEvent({headers:{cookie:'unrelated=password-token'},body:{action:'login',username:'student',password:'NEVER_CAPTURE_PASSWORD',note:'PRIVATE_TICKET_TEXT'}},'auth',401,1250,requestId,{error:'arbitrary sensitive text'});assert.equal(event.actor,'student');assert.equal(event.identity,'attempted');for(const secret of ['NEVER_CAPTURE_PASSWORD','PRIVATE_TICKET_TEXT','password-token','arbitrary sensitive text'])assert.equal(JSON.stringify(event).includes(secret),false);const browser=browserDiagnostic({...entry,password:'SECRET',actor:'forged',code:'forged'},{username:'verified'});assert.equal(browser.actor,'verified');assert.equal(browser.code,'http-503');assert.equal(JSON.stringify(browser).includes('SECRET'),false);assert.equal(browserDiagnostic({...entry,durationMs:Infinity},{username:'verified'}),null);}finally{if(old==null)delete process.env.SPINNER_BRIDGE_TOKEN;else process.env.SPINNER_BRIDGE_TOKEN=old;}
});
test('private storage checks owner on reads, strips session tokens, suppresses shared access and uses bounded ring slots',()=>{
 const {ctx,props,rows,created,permissions,writes}=school();assert.equal(ctx.diagnosticDispatch_({action:'auth-diagnostics-read',session:'student'}).status,403);assert.equal(ctx.diagnosticDispatch_({action:'auth-diagnostics-read',session:'bad'}).status,401);assert.equal(ctx.diagnosticDispatch_({action:'diagnostics-record',entries:[{...entry,_session:'student',password:'SECRET'}]}).status,200);assert.equal(created.length,1);assert.deepEqual(permissions,['domain']);assert.equal(rows[0][8],'student');assert.equal(rows[0][9],'verified');assert.equal(JSON.stringify(rows).includes('_session'),false);assert.equal(JSON.stringify(rows).includes('SECRET'),false);const read=ctx.diagnosticDispatch_({action:'auth-diagnostics-read',session:'owner'});assert.equal(read.events[0].durationMs,14000);assert.equal('session' in read.events[0],false);props.set('diagnostic-counter','5000');ctx.diagnosticDispatch_({action:'diagnostics-record',entries:[entry]});assert.equal(writes.at(-1).data[0].range,"'Events'!A2:K2");assert.equal(created.length,1);assert.equal(ctx.diagnosticDispatch_({action:'diagnostics-record',session:'bad',entries:[entry]}).status,401);
});
test('diagnostics endpoint denies unsigned readers and verified student identities before retrieving history',async()=>{
 let res=response();await handler({method:'GET',headers:{}},res);assert.equal(res.statusCode,401);const old=process.env.SPINNER_BRIDGE_TOKEN;process.env.SPINNER_BRIDGE_TOKEN='test-secret';try{const identity=signedIdentity(session,{username:'student',email:'student@students.bethelsd.org',expires:Date.now()+60000});res=response();await handler({method:'GET',headers:{cookie:`${COOKIE}=${session}; ${IDENTITY}=${identity}`}},res);assert.equal(res.statusCode,403);assert.equal(res.data.events,undefined);assert.match(res.headers['Cache-Control'],/no-store/);}finally{if(old==null)delete process.env.SPINNER_BRIDGE_TOKEN;else process.env.SPINNER_BRIDGE_TOKEN=old;}
});
test('tracking wrapper preserves successful and failed responses and never breaks on missing metadata',async()=>{const fn=withDiagnostics('auth',async(_req,res)=>res.status(401).json({error:'Sign-in rejected'})),res=response();await fn({method:'POST'},res);assert.equal(res.statusCode,401);assert.equal(res.data.error,'Sign-in rejected');assert.match(res.headers['X-NEST-Request-ID'],/^[a-f0-9-]{36}$/);});
const settle=()=>new Promise(resolve=>setTimeout(resolve,15));
test('owner dashboard merges both measurements, copies a safe error report and clears on identity changes',async()=>{
 const dom=new JSDOM(fs.readFileSync('profile.html','utf8'),{url:'https://gknest.org/profile#diagnostics',runScripts:'outside-only'}),w=dom.window;let copied;Object.defineProperty(w.navigator,'clipboard',{value:{writeText:async value=>{copied=value;}}});w.AbortSignal=AbortSignal;w.NestAuth={identity:{signedIn:true,email:'mario@memberhq.net'},ready:Promise.resolve()};w.fetch=async()=>({ok:true,json:async()=>({events:[{...entry,time:new Date().toISOString()},{...entry,id:'browser',time:new Date().toISOString(),phase:'browser',durationMs:15000,identity:'verified'}]})});w.eval(fs.readFileSync('js/profile.js','utf8'));w.eval(fs.readFileSync('js/diagnostics.js','utf8'));await settle();const d=w.document;assert.equal(d.getElementById('diagnostics-workspace').hidden,false);assert.equal(d.querySelectorAll('#diagnostics-rows tr').length,1);d.querySelector('#diagnostics-rows button').click();await settle();assert.match(copied,/browser 15.00s; server 14.00s/);assert.match(copied,/http-503/);assert.match(copied,/Request ID:/);w.NestAuth.identity={signedIn:true,email:'student@students.bethelsd.org'};d.dispatchEvent(new w.Event('nest-auth-change'));await settle();assert.equal(d.getElementById('diagnostics-workspace').hidden,true);assert.equal(d.getElementById('diagnostics-report').value,'');assert.equal(d.getElementById('diagnostics-rows').textContent,'');dom.window.close();
});
test('browser monitor records metadata only, excludes diagnostics recursion and clears on logout',async()=>{
 const dom=new JSDOM('<!doctype html>',{url:'https://gknest.org/service',runScripts:'outside-only'}),w=dom.window,calls=[];w.NestAuth={identity:{signedIn:true,username:'student'}};w.AbortSignal=AbortSignal;const native=w.setTimeout.bind(w);w.setTimeout=(fn,ms)=>ms===2000?native(fn,1):native(fn,ms);w.fetch=async(url,options)=>{calls.push({url,body:options?.body});return {ok:true,status:200,headers:{get:()=>requestId}};};w.eval(fs.readFileSync('js/access-diagnostics.js','utf8'));await w.fetch('/api/auth',{method:'POST',body:JSON.stringify({action:'login',username:'student',password:'NEVER_SAVE_THIS'})});await settle();const report=calls.find(c=>c.url==='/api/diagnostics');assert.ok(report);assert.equal(report.body.includes('NEVER_SAVE_THIS'),false);assert.equal(JSON.parse(report.body).events[0].operation,'login');assert.equal(calls.filter(c=>c.url==='/api/diagnostics').length,1);w.NestAuth.identity=null;w.document.dispatchEvent(new w.Event('nest-auth-change'));assert.equal(w.sessionStorage.getItem('nest-access-metadata'),'[]');dom.window.close();
});
