import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import {createHash} from 'node:crypto';import {JSDOM} from 'jsdom';import handler from '../api/fabrication.mjs';
const source=fs.readFileSync('google-spinner/Fabrication.js','utf8'),hash=v=>createHash('sha256').update(v).digest('hex');
function context(){
 const heads=['Status','Status Log','Notes','Timestamp','Email Address','Choose your name','Fabrication method','Upload your file'];
 const raw=['Printing','Private history with names','Private notes',46295.4,'student@students.bethelsd.org','Student, Test_Period 2','WAZER water cutting','https://drive.google.com/file/d/test'];
 const state={events:[],writes:[],mail:[],rows:[raw]},leaders=[['Period 2','','Fabrication Supervisor','','supervisor@students.bethelsd.org'],['Period CTSO','','Chief Financial Officer','','cfo@students.bethelsd.org']];
 const sheets={get:()=>({sheets:[{properties:{sheetId:1,title:'WAZER',gridProperties:{rowCount:100}}},{properties:{sheetId:2,title:'FabricationWebLog',gridProperties:{rowCount:20000}}}]}),Values:{get:(_id,range)=>({values:range.includes('Imported')?leaders:state.events}),batchGet:(_id,options)=>({valueRanges:[{values:options.ranges[0].includes('A3')?[heads]:state.rows}]})},batchUpdate:body=>{state.writes.push(body);for(const r of body.requests){if(r.appendCells)state.events.push(r.appendCells.rows[0].values.map(v=>v.userEnteredValue.stringValue));if(r.updateCells)state.rows[r.updateCells.range.startRowIndex-3][r.updateCells.range.startColumnIndex]=r.updateCells.rows[0].values[0].userEnteredValue.stringValue;}return {};}};
 const ctx=vm.createContext({Sheets:{Spreadsheets:sheets},LEADERSHIP_DATABASE:'leadership',OWNER_EMAILS:['owner@bethelsd.org'],email_:v=>String(v||'').toLowerCase(),districtEmail_:v=>v.endsWith('@students.bethelsd.org')?v:'',memberEmail_:v=>v,hash_:hash,Utilities:{getUuid:()=>`event-${state.events.length}`},MailApp:{sendEmail:v=>state.mail.push(v)},Date,console});vm.runInContext(source,ctx);return {ctx,state,leaders};
}
test('current supervisor, manager and executive roles authorize; former title and ordinary students do not',()=>{const {ctx,leaders}=context();assert.equal(ctx.fabAllowed_('supervisor@students.bethelsd.org',leaders),true);assert.equal(ctx.fabAllowed_('cfo@students.bethelsd.org',leaders),true);assert.equal(ctx.fabAllowed_('student@students.bethelsd.org',leaders),false);for(const role of ['Division Manager','Assistant Manager','Chief Executive Officer','Chief Operations Officer'])assert.equal(ctx.fabAllowed_('role@students.bethelsd.org',[[role.startsWith('Chief')?'Period CTSO':'Period 2','',role,'','role@students.bethelsd.org']]),true);assert.equal(ctx.fabAllowed_('old@students.bethelsd.org',[['Period 2','','3d Print Specialist','','old@students.bethelsd.org']]),false);});
test('public queue strips identities, files, private notes and legacy history',()=>{const {ctx}=context(),data=ctx.fabView_('',0);assert.equal(data.requests[0].status,'In progress');for(const secret of ['student@','Student,','drive.google','Private'])assert.equal(JSON.stringify(data).includes(secret),false);assert.equal(ctx.fabView_('student@students.bethelsd.org',0).status,403);});
test('saving is atomic with audit history; stale versions and ordinary students cannot write',()=>{const {ctx,state}=context(),item=ctx.fabView_('supervisor@students.bethelsd.org',0).requests[0],body={action:'auth-fabrication-update',id:item.id,version:item.version,status:'Ready for pickup',publicNote:'Collect at the station.',notes:'Private note'};assert.equal(ctx.fabWrite_('student@students.bethelsd.org',body).status,403);assert.equal(state.writes.length,0);assert.equal(ctx.fabWrite_('supervisor@students.bethelsd.org',body).status,200);assert.equal(state.writes.length,1);assert.equal(state.writes[0].requests.length,4);assert.equal(state.rows[0][0],'Ready for pickup');assert.equal(state.mail.length,0);assert.equal(ctx.fabWrite_('supervisor@students.bethelsd.org',body).status,409);assert.equal(ctx.fabView_('',0).requests[0].updates[0].note,body.publicNote);});
test('email uses stored requestor only and prevents duplicate attempts',()=>{const {ctx,state}=context();let item=ctx.fabView_('supervisor@students.bethelsd.org',0).requests[0];ctx.fabWrite_('supervisor@students.bethelsd.org',{action:'auth-fabrication-update',id:item.id,version:item.version,status:'Done',publicNote:'Ready.',notes:''});item=ctx.fabView_('supervisor@students.bethelsd.org',0).requests[0];const body={action:'auth-fabrication-email',id:item.id,version:item.version,eventId:item.updates.at(-1).eventId,to:'attacker@example.com'};assert.equal(ctx.fabWrite_('supervisor@students.bethelsd.org',body).status,200);assert.equal(state.mail[0].to,'student@students.bethelsd.org');assert.equal(ctx.fabWrite_('supervisor@students.bethelsd.org',body).status,409);assert.equal(state.mail.length,1);});
test('stable IDs follow sorted rows; ambiguous duplicates reject updates',()=>{const {ctx,state}=context(),item=ctx.fabView_('supervisor@students.bethelsd.org',0).requests[0];state.rows.unshift([]);assert.equal(ctx.fabView_('supervisor@students.bethelsd.org',0).requests[0].id,item.id);state.rows.push([...state.rows[1]]);assert.equal(ctx.fabWrite_('supervisor@students.bethelsd.org',{id:item.id,version:item.version}).status,409);});
function response(){return {setHeader(){},status(code){this.code=code;return this;},json(data){this.data=data;return this;}};}
test('website denies unauthenticated management and cross-origin writes',async()=>{const res=response();await handler({method:'GET',headers:{},query:{manage:'1'}},res);assert.equal(res.code,401);const cross=response();await handler({method:'POST',headers:{origin:'https://evil.example','content-type':'application/json',cookie:'__Host-nest-auth='+'a'.repeat(64)},body:{action:'email'}},cross);assert.equal(cross.code,403);});
test('public website projection strips unexpected private bridge data',async()=>{const old=globalThis.fetch;process.env.SPINNER_BRIDGE_URL='https://script.google.com/test';process.env.SPINNER_BRIDGE_TOKEN='test';globalThis.fetch=async()=>({ok:true,json:async()=>({status:200,requests:[{id:'a'.repeat(64),status:'Queued',machine:'Bambu',updates:[],email:'private',notes:'private',fields:[]}],total:1})});try{const res=response();await handler({method:'GET',headers:{},query:{}},res);assert.equal(res.code,200);assert.equal(JSON.stringify(res.data).includes('private'),false);}finally{globalThis.fetch=old;delete process.env.SPINNER_BRIDGE_URL;delete process.env.SPINNER_BRIDGE_TOKEN;}});
test('management clears private content on logout and preserves unsaved drafts',async()=>{const dom=new JSDOM(fs.readFileSync('print-management.html','utf8'),{runScripts:'outside-only',url:'https://gknest.org/print-management'}),w=dom.window;let calls=0;w.NestAuth={identity:{signedIn:true},ready:Promise.resolve(),open(){}};w.fetch=async()=>{calls++;return {ok:true,json:async()=>({requests:[{id:'a'.repeat(64),version:'b'.repeat(64),name:'Test',email:'test@students.bethelsd.org',machine:'Laser cutter',status:'Queued',notes:'private',legacyLog:'history',fields:[],updates:[],canUpdate:true,emailState:'none'}],statuses:['Queued','Done'],total:1})};};w.eval(fs.readFileSync('js/fabrication.js','utf8'));await new Promise(r=>setTimeout(r,10));w.document.querySelector('.fabrication-request').click();assert.equal(w.document.querySelector('#fabrication-detail').hidden,false);assert.equal(w.document.querySelector('#fabrication-email').disabled,true);w.document.querySelector('#fabrication-notes').value='draft';w.document.querySelector('#fabrication-notes').dispatchEvent(new w.Event('input',{bubbles:true}));w.confirm=()=>false;w.document.querySelector('#fabrication-refresh').click();assert.equal(calls,1);w.NestAuth.identity.signedIn=false;w.document.dispatchEvent(new w.Event('nest-auth-change'));assert.equal(w.document.querySelector('#fabrication-detail').hidden,true);assert.equal(w.document.querySelector('#fabrication-notes').value,'');dom.window.close();});
