import division from './division.mjs';
import { nestHeader, nestFooter } from '../lib/nest-page-shell.mjs';
import { DIVISIONS } from '../lib/divisions.mjs';
import { HQ_LOOKUP_HTML, HQ_JOBS_HTML, HQ_HIRING_HTML } from '../lib/division-hq-content.mjs';
const escape=value=>String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const scriptJSON=value=>JSON.stringify(value).replace(/</g,'\\u003c').replace(/\u2028/g,'\\u2028').replace(/\u2029/g,'\\u2029');
export function renderDivisionPage(period,data,code=200){
 const label=period==='CTSO'?'NEST™ Robotics':'Division '+period;
 const allowed=code===200&&data?.manager&&Array.isArray(data.leaders);
 const icon=`<img class="division-hq-header-icon" src="/assets/division-icons/${period==='CTSO'?'ctso':'division-'+escape(period)}-512.webp" alt="${escape(period==='CTSO'?'CTSO':'Division '+period)} official badge" width="144" height="144">`;
 const content=allowed?`<main class="division-workspace division-page" data-period="${escape(period)}"><div class="division-window-layout">
 <div class="division-page-intro"><div class="division-hq-heading">${icon}<div><p class="division-eyebrow">Division HQ</p><h1>${escape(label)}</h1><p>Your team, meetings, and opportunities in one place.</p></div></div><nav class="division-page-actions" aria-label="Division actions"><a class="division-hq-back" href="/divisions">All divisions</a></nav></div>
 <div class="division-hq-content"><div class="division-hq-tabs" role="tablist" aria-label="${escape(label)} workspace">
 ${[['lookup','Team Lookup'],['meetings','Meetings'],['employment','Employment'],['hiring','Hiring']].map(([key,title])=>`<button type="button" role="tab" id="hq-tab-${key}" aria-controls="hq-panel-${key}" aria-selected="false" tabindex="-1" data-hq-tab="${key}"${key==='hiring'?` data-hiring${data.canManage?'':' hidden'}`:''}>${title}</button>`).join('')}
 </div><p class="division-window-status" role="status" aria-live="polite"></p>
 <section role="tabpanel" id="hq-panel-lookup" aria-labelledby="hq-tab-lookup" tabindex="0" hidden><section class="division-team"><h2>Current leadership team</h2><div data-team-summary></div></section><div class="leadership-page" data-hq-lookup="${escape(period)}">${HQ_LOOKUP_HTML.replaceAll('src="assets/','src="/assets/')}</div></section>
 <section role="tabpanel" id="hq-panel-meetings" aria-labelledby="hq-tab-meetings" tabindex="0" hidden><h2>Meetings</h2><nav class="division-window-positions" aria-label="Leadership positions and slides"></nav><section class="division-slideshow"><h3>Manager slideshow</h3><div class="division-window-controls"><button type="button" data-load disabled>Load division slides</button><p></p><button type="button" data-edit-manager hidden>Edit manager slide</button></div><div class="division-window-stage"></div><div class="division-window-footer"><small>Use your school Google account to view and edit slides.</small><button type="button" data-refresh>Refresh team and slideshow</button></div></section></section>
 <section role="tabpanel" id="hq-panel-employment" aria-labelledby="hq-tab-employment" tabindex="0" hidden><h2>Employment</h2><p>Explore the division positions below, then choose ${escape(label)} in the application form. Positions may be shared by partners.</p>${HQ_JOBS_HTML}<section class="division-employment-form"><h3>Apply for a leadership position</h3><iframe data-application-src="https://docs.google.com/forms/d/e/1FAIpQLSdy-5_36M3kbapsQRVni1Kn11LBXtq7PTdqPTS8lm44EZjjZA/viewform?embedded=true" title="NEST leadership application" loading="lazy"></iframe><p>If the form does not load, <a data-external href="https://docs.google.com/forms/d/e/1FAIpQLSdy-5_36M3kbapsQRVni1Kn11LBXtq7PTdqPTS8lm44EZjjZA/viewform" target="_blank" rel="noopener noreferrer">open it in Google</a>.</p></section></section>
 ${data.canManage?`<section role="tabpanel" id="hq-panel-hiring" aria-labelledby="hq-tab-hiring" tabindex="0" hidden><div class="internal-page hiring-page" data-hiring-period="${escape(period)}">${HQ_HIRING_HTML}</div></section>`:''}
 </div></div></main><script type="application/json" id="division-bootstrap">${scriptJSON(data)}</script>`:
 `<main class="division-page-lock"><div class="division-hq-heading">${icon}<div><p class="division-eyebrow">Division HQ</p><h1>${escape(label)}</h1></div></div><p role="status">${escape(data?.error||'This division is unavailable.')}</p>${code===401?'<button type="button" data-sign-in>Sign in to NEST</button>':''}${code===503?'<button type="button" data-retry>Try again</button>':''}<p><a href="/divisions">Back to Division HQ</a></p></main>`;
 return `<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escape(label)} · NEST™</title><link rel="stylesheet" href="/css/styles.css"><link rel="stylesheet" href="/css/nest-auth.css"><link rel="stylesheet" href="/css/resource-viewer.css"><link rel="stylesheet" href="/css/internal-workspaces.css"><link rel="stylesheet" href="/css/hiring-workspace.css"><link rel="stylesheet" href="/css/division-workspace.css"><link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;600;700;800&display=swap" rel="stylesheet"></head><body><div class="bg-watermark"></div>${nestHeader}${content}${allowed&&data.identity?`<script type="application/json" id="nest-auth-bootstrap">${scriptJSON(data.identity)}</script>`:''}${nestFooter}<script src="/js/nest-auth.js"></script><script src="/js/division-hq.js"></script><script src="/js/division-workspace.js"></script><script src="/js/main.js"></script><script src="/js/resource-viewer.js"></script></body></html>`;
}
export default async function handler(req,res){
 res.setHeader('Cache-Control','private, no-store, max-age=0');res.setHeader('Vercel-CDN-Cache-Control','no-store');res.setHeader('Vary','Cookie');res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Content-Type','text/html; charset=utf-8');res.setHeader('X-Robots-Tag','noindex, nofollow');
 if(req.method!=='GET'){res.setHeader('Allow','GET');return res.status(405).send('Method not allowed.');}
 const period=String(req.query?.period||'');
 if(!Object.hasOwn(DIVISIONS,period))return res.status(404).send('Division not found.');
 let code=200,data;
 // Reuse the same live membership check before returning any team or deck data.
 await division({method:req.method,headers:req.headers,query:{period}}, {setHeader(name,value){if(name==='Server-Timing')res.setHeader(name,value);},status(value){code=value;return this;},json(value){data=value;return this;}});
 return res.status(code).send(renderDivisionPage(period,data,code));
}
